
# game_statistics.py  —  Explain My Move  v1.3
# Author: Ammar
# OCR A-Level Computer Science NEA — Component 03/04
#
# Contains:
#   PlayerStats           (dataclass)     — per-player statistics record
#   GameStats             (dataclass)     — whole-game statistics record
#   StatisticsCalculator  (Design Class 8) — computes accuracy and game summary
#
# Purpose:
#   After a PGN game review is complete, StatisticsCalculator processes the
#   list of ReviewEntry dicts generated by the review pipeline and produces:
#       • An accuracy percentage for White and Black (0–100%)
#       • Counts of Brilliant/Best/Good/Inaccuracy/Mistake/Blunder per player
#       • Game phase breakdown (Opening/Middlegame/Endgame by move number)
#       • Worst move identification (highest centipawn loss)
#       • Plain-English summary text in Beginner or Intermediate mode
#
# Integration:
#   Called from ExplainMyMoveApp._analyse_pgn() after _review_moves is populated.
#   Results are passed to the GUI for display in the statistics panel.
#
# ─────────────────────────────────────────────────────────────────────────────
# DESIGN JUSTIFICATION (NEA Section 3.2.2(d) — Class 8)
# ─────────────────────────────────────────────────────────────────────────────
#   Separating statistics from the review pipeline (BadMoveAnalyser) respects
#   the Single Responsibility Principle: BadMoveAnalyser classifies individual
#   moves; StatisticsCalculator aggregates them across a whole game.
#   Using dataclasses ensures immutable, validated result objects that the GUI
#   can render without modifying — consistent with how BadMoveResult works.
#
# ─────────────────────────────────────────────────────────────────────────────
# ACCURACY FORMULA  (self-designed — documented for NEA evidence)
# ─────────────────────────────────────────────────────────────────────────────
#   Each move is assigned a move_accuracy score using an Elo-inspired
#   win-probability model:
#
#       win_prob(cp) = 1 / (1 + exp(−cp / 256))
#           ↳ Logistic function; 256 centipawns ≈ one standard deviation
#             in typical Elo-based chess scoring.
#
#       prob_before = 0.5   (neutral baseline — the position before the move
#                            is assumed balanced for the moving player)
#       prob_after  = win_prob(−cp_loss)
#           ↳ A positive cp_loss means the moving player lost ground, so
#             the "win probability after" is calculated from −cp_loss.
#
#       delta = prob_before − prob_after  (how much win probability was lost)
#
#       move_accuracy = max(0.0, 100.0 × (1 − 2 × delta))
#           ↳ Linear mapping: delta=0 → 100%, delta=0.5 → 0%.
#             The factor of 2 ensures the scale spans the full [0,100] range
#             since delta can at most be 0.5 (from 50% to 0%).
#
#   Game accuracy for each player = mean of all their move_accuracy values,
#   clamped to [0, 100].
#
#   Verification:
#       cp_loss = 0   → prob_after = 0.5  → delta = 0   → accuracy = 100%  ✓
#       cp_loss = 256 → prob_after = 0.27 → delta = 0.23 → accuracy ≈ 54%  ✓
#       cp_loss = 512 → prob_after = 0.12 → delta = 0.38 → accuracy ≈ 24%  ✓
#
#   Justification: A pure centipawn-loss formula (e.g., accuracy = 100−cp/10)
#   treats all centipawn losses linearly, which is misleading — going from +5.0
#   to +4.0 (100 cp) is very different from going from 0.0 to −1.0 (100 cp).
#   The logistic model correctly weights losses relative to the game state.


import math
from dataclasses import dataclass, field

import chess



# CONSTANTS


# Move number boundaries for game phase detection.
# Opening:    moves 1–10  (development, centre, castling)
# Middlegame: moves 11–30 (tactical and positional play)
# Endgame:    moves 31+   (king activation, pawn promotion)
OPENING_END     = 10
MIDDLEGAME_END  = 30

# Logistic scaling factor (centipawns per standard deviation).
# 256 cp is a widely used value in chess rating mathematics.
_WIN_PROB_SCALE = 256.0



# DATA CLASSES


@dataclass
class PlayerStats:
    """
    Holds all computed statistics for one player (White or Black) in a game.

    Attributes:
        colour              — chess.WHITE or chess.BLACK
        accuracy            — overall accuracy percentage [0.0, 100.0]
        brilliant_count     — number of Brilliant moves (not classified by engine
                              in v1.3; reserved for future engine annotation)
        best_count          — number of Best/OK moves
        good_count          — number of Good moves (small cp_loss, within OK)
        inaccuracy_count    — number of Inaccuracy moves
        mistake_count       — number of Mistake moves
        blunder_count       — number of Blunder moves
        total_moves         — total half-moves played by this player
        total_cp_loss       — cumulative centipawn loss across all moves
        avg_cp_loss         — mean centipawn loss per move
        worst_move_san      — SAN of the single worst move (highest cp_loss)
        worst_move_cp_loss  — centipawn loss of the worst move
        worst_move_number   — full move number of the worst move
        phase_accuracy      — dict: {"Opening": float, "Middlegame": float, "Endgame": float}
    """
    colour:             int   = chess.WHITE
    accuracy:           float = 0.0
    brilliant_count:    int   = 0
    best_count:         int   = 0
    good_count:         int   = 0
    inaccuracy_count:   int   = 0
    mistake_count:      int   = 0
    blunder_count:      int   = 0
    total_moves:        int   = 0
    total_cp_loss:      int   = 0
    avg_cp_loss:        float = 0.0
    worst_move_san:     str   = "—"
    worst_move_cp_loss: int   = 0
    worst_move_number:  int   = 0
    phase_accuracy:     dict  = field(default_factory=lambda: {
        "Opening": 100.0, "Middlegame": 100.0, "Endgame": 100.0
    })


@dataclass
class GameStats:
    """
    Holds combined statistics for an entire game.

    Attributes:
        white              — PlayerStats for White
        black              — PlayerStats for Black
        total_half_moves   — total half-moves in the game
        opening_moves      — half-moves in the opening phase
        middlegame_moves   — half-moves in the middlegame phase
        endgame_moves      — half-moves in the endgame phase
        sharpest_position  — move number with the highest cp_loss in the game
    """
    white:             PlayerStats = field(default_factory=PlayerStats)
    black:             PlayerStats = field(default_factory=PlayerStats)
    total_half_moves:  int         = 0
    opening_moves:     int         = 0
    middlegame_moves:  int         = 0
    endgame_moves:     int         = 0
    sharpest_position: int         = 0



# STATISTICS CALCULATOR  (Design Class 8)


class StatisticsCalculator:
    """
    Computes accuracy scores and game statistics from a completed PGN review.

    Input:
        review_entries  — list of ReviewEntry dicts as produced by
                          ExplainMyMoveApp._analyse_pgn().
                          Each dict must contain at minimum:
                            'color'          : chess.WHITE or chess.BLACK
                            'move_num'       : int (full move number)
                            'move_san'       : str
                            'cp_loss'        : int (>= 0)
                            'classification' : str

    Methods (public):
        calculate(review_entries)   → GameStats
        get_summary_text(stats, mode) → str
        move_accuracy(cp_loss)      → float   (class method — also useful externally)

    Algorithm:
        1. Separate entries by colour (White / Black).
        2. For each entry, compute move_accuracy(cp_loss) using the logistic model.
        3. Group move accuracies by game phase (Opening / Middlegame / Endgame).
        4. Compute per-phase and overall accuracy as arithmetic means.
        5. Identify worst move (maximum cp_loss).
        6. Count classifications.
        7. Return GameStats with White and Black PlayerStats populated.

    Design justification:
        A stateless calculator (no __init__ state beyond method calls) allows
        the same instance to be reused across multiple games without risking
        stale data — consistent with the stateless design of OutputFormatter.
    """

    # ── Public entry point ────────────────────────────────────────────────────

    def calculate(self, review_entries: list) -> GameStats:
        """
        Processes all review entries and returns a GameStats object.

        Parameters:
            review_entries  — list of dicts from the PGN review pipeline

        Returns:
            GameStats with fully populated White and Black PlayerStats.
        """
        if not review_entries:
            return GameStats()

        white_entries = [e for e in review_entries if e["color"] == chess.WHITE]
        black_entries = [e for e in review_entries if e["color"] == chess.BLACK]

        white_stats = self._compute_player_stats(white_entries, chess.WHITE)
        black_stats = self._compute_player_stats(black_entries, chess.BLACK)

        # Count half-moves per phase
        opening_count    = sum(1 for e in review_entries
                               if self._phase_label(e["move_num"]) == "Opening")
        middlegame_count = sum(1 for e in review_entries
                               if self._phase_label(e["move_num"]) == "Middlegame")
        endgame_count    = sum(1 for e in review_entries
                               if self._phase_label(e["move_num"]) == "Endgame")

        # Sharpest position: move number with the highest cp_loss in the game
        sharpest = max(review_entries, key=lambda e: e["cp_loss"], default=None)
        sharpest_move_num = sharpest["move_num"] if sharpest else 0

        return GameStats(
            white             = white_stats,
            black             = black_stats,
            total_half_moves  = len(review_entries),
            opening_moves     = opening_count,
            middlegame_moves  = middlegame_count,
            endgame_moves     = endgame_count,
            sharpest_position = sharpest_move_num,
        )

    def get_summary_text(self, stats: GameStats, mode: str = "Beginner") -> str:
        """
        Returns a plain-English summary of the game statistics.

        In Beginner mode: avoids centipawn jargon; uses descriptive phrases.
        In Intermediate mode: includes centipawn loss figures and phase breakdown.

        Parameters:
            stats  — GameStats returned by calculate()
            mode   — "Beginner" or "Intermediate"

        Returns:
            A formatted multi-line string suitable for display in the GUI panel.
        """
        if mode == "Beginner":
            return self._beginner_summary(stats)
        else:
            return self._intermediate_summary(stats)

    @classmethod
    def move_accuracy(cls, cp_loss: int) -> float:
        """
        Converts a single move's centipawn loss to an accuracy score [0.0, 100.0].

        Uses the logistic win-probability model documented at the top of this file.
        Exposed as a classmethod so it can be called standalone for unit testing
        and for future move-by-move accuracy display in the GUI.

        Parameters:
            cp_loss  — centipawn loss for a move (>= 0; negative values treated as 0)

        Returns:
            float in [0.0, 100.0]
        """
        cp_loss = max(0, cp_loss)
        if cp_loss == 0:
            return 100.0

        prob_before = 0.5
        prob_after  = cls._win_probability(-cp_loss)
        delta       = prob_before - prob_after
        accuracy    = max(0.0, 100.0 * (1.0 - 2.0 * delta))
        return round(accuracy, 2)

    # ── Private helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _win_probability(cp: int) -> float:
        """
        Logistic win probability from a centipawn score.
        Returns a value in (0, 1): > 0.5 means advantage for the scoring side.

        Parameters:
            cp  — centipawn score from the moving player's perspective
        """
        try:
            return 1.0 / (1.0 + math.exp(-cp / _WIN_PROB_SCALE))
        except OverflowError:
            # exp() overflows for very large negative cp (catastrophic positions)
            return 0.0

    @staticmethod
    def _phase_label(move_num: int) -> str:
        """
        Returns the game phase label for a given full move number.

        Boundaries:
            Opening:    moves 1–10
            Middlegame: moves 11–30
            Endgame:    moves 31+

        Design note: These boundaries are commonly used in chess literature as
        rough phase guides. A more sophisticated approach could use material
        count, but move number is transparent and documentable for the NEA.
        """
        if move_num <= OPENING_END:
            return "Opening"
        elif move_num <= MIDDLEGAME_END:
            return "Middlegame"
        else:
            return "Endgame"

    def _compute_player_stats(self, entries: list, colour: int) -> PlayerStats:
        """
        Computes PlayerStats for one player from their list of review entries.

        Parameters:
            entries  — list of ReviewEntry dicts for this player only
            colour   — chess.WHITE or chess.BLACK
        """
        if not entries:
            stats = PlayerStats(colour=colour)
            return stats

        stats = PlayerStats(colour=colour)
        stats.total_moves = len(entries)

        # Accuracy scores per phase
        phase_scores: dict[str, list[float]] = {
            "Opening": [], "Middlegame": [], "Endgame": []
        }

        all_accuracies: list[float] = []
        worst_cp_loss    = 0
        worst_move_san   = "—"
        worst_move_num   = 0
        total_cp         = 0

        for entry in entries:
            cp_loss   = max(0, entry.get("cp_loss", 0))
            total_cp += cp_loss

            acc   = self.move_accuracy(cp_loss)
            phase = self._phase_label(entry.get("move_num", 1))

            all_accuracies.append(acc)
            phase_scores[phase].append(acc)

            # Track worst move
            if cp_loss > worst_cp_loss:
                worst_cp_loss  = cp_loss
                worst_move_san = entry.get("move_san", "—")
                worst_move_num = entry.get("move_num", 0)

            # Count classification
            cls_label = entry.get("classification", "OK")
            if cls_label in ("OK", "Best"):
                stats.best_count += 1
            elif cls_label == "Good":
                stats.good_count += 1
            elif cls_label == "Inaccuracy":
                stats.inaccuracy_count += 1
            elif cls_label == "Mistake":
                stats.mistake_count += 1
            elif cls_label == "Blunder":
                stats.blunder_count += 1

        # Overall accuracy
        stats.accuracy  = round(sum(all_accuracies) / len(all_accuracies), 1)
        stats.total_cp_loss  = total_cp
        stats.avg_cp_loss    = round(total_cp / len(entries), 1)
        stats.worst_move_san = worst_move_san
        stats.worst_move_cp_loss = worst_cp_loss
        stats.worst_move_number  = worst_move_num

        # Per-phase accuracy
        for phase, scores in phase_scores.items():
            if scores:
                stats.phase_accuracy[phase] = round(
                    sum(scores) / len(scores), 1
                )

        return stats

    def _beginner_summary(self, stats: GameStats) -> str:
        """Beginner-friendly summary using plain English, no centipawn jargon."""
        w = stats.white
        b = stats.black

        def _grade(acc: float) -> str:
            if acc >= 90:
                return "Excellent"
            elif acc >= 75:
                return "Good"
            elif acc >= 60:
                return "Fair"
            elif acc >= 40:
                return "Below average"
            else:
                return "Needs improvement"

        lines = [
            "═" * 48,
            "  GAME SUMMARY",
            "═" * 48,
            "",
            f"  White accuracy:  {w.accuracy:.1f}%  ({_grade(w.accuracy)})",
            f"  Black accuracy:  {b.accuracy:.1f}%  ({_grade(b.accuracy)})",
            "",
            "  WHITE BREAKDOWN:",
            f"    Best moves:    {w.best_count}",
            f"    Inaccuracies:  {w.inaccuracy_count}",
            f"    Mistakes:      {w.mistake_count}",
            f"    Blunders:      {w.blunder_count}",
        ]
        if w.worst_move_san != "—":
            lines.append(f"    Worst move:    {w.worst_move_san}"
                         f" (move {w.worst_move_number})")

        lines += [
            "",
            "  BLACK BREAKDOWN:",
            f"    Best moves:    {b.best_count}",
            f"    Inaccuracies:  {b.inaccuracy_count}",
            f"    Mistakes:      {b.mistake_count}",
            f"    Blunders:      {b.blunder_count}",
        ]
        if b.worst_move_san != "—":
            lines.append(f"    Worst move:    {b.worst_move_san}"
                         f" (move {b.worst_move_number})")

        lines += [
            "",
            f"  Total moves analysed: {stats.total_half_moves}",
            "═" * 48,
        ]
        return "\n".join(lines)

    def _intermediate_summary(self, stats: GameStats) -> str:
        """Intermediate summary with centipawn figures and phase breakdown."""
        w = stats.white
        b = stats.black

        lines = [
            "═" * 56,
            "  GAME STATISTICS  (Intermediate)",
            "═" * 56,
            "",
            f"  {'':20}  {'WHITE':>10}  {'BLACK':>10}",
            f"  {'─'*20}  {'─'*10}  {'─'*10}",
            f"  {'Accuracy':20}  {w.accuracy:>9.1f}%  {b.accuracy:>9.1f}%",
            f"  {'Avg CP Loss':20}  {w.avg_cp_loss:>10.1f}  {b.avg_cp_loss:>10.1f}",
            f"  {'Total CP Loss':20}  {w.total_cp_loss:>10}  {b.total_cp_loss:>10}",
            f"  {'Best/OK moves':20}  {w.best_count:>10}  {b.best_count:>10}",
            f"  {'Inaccuracies':20}  {w.inaccuracy_count:>10}  {b.inaccuracy_count:>10}",
            f"  {'Mistakes':20}  {w.mistake_count:>10}  {b.mistake_count:>10}",
            f"  {'Blunders':20}  {w.blunder_count:>10}  {b.blunder_count:>10}",
            "",
            "  PHASE ACCURACY:",
            f"  {'Phase':20}  {'White':>10}  {'Black':>10}",
            f"  {'─'*20}  {'─'*10}  {'─'*10}",
        ]
        for phase in ("Opening", "Middlegame", "Endgame"):
            wa = w.phase_accuracy.get(phase, "—")
            ba = b.phase_accuracy.get(phase, "—")
            wa_s = f"{wa:.1f}%" if isinstance(wa, float) else wa
            ba_s = f"{ba:.1f}%" if isinstance(ba, float) else ba
            lines.append(f"  {phase:20}  {wa_s:>10}  {ba_s:>10}")

        lines += [
            "",
            "  WORST MOVES:",
            f"  White: {w.worst_move_san} (move {w.worst_move_number})"
            f" — {w.worst_move_cp_loss} cp loss",
            f"  Black: {b.worst_move_san} (move {b.worst_move_number})"
            f" — {b.worst_move_cp_loss} cp loss",
            "",
            f"  Total half-moves: {stats.total_half_moves}  |  "
            f"Sharpest at move: {stats.sharpest_position}",
            "═" * 56,
        ]
        return "\n".join(lines)
